version: '3.7'


services: 
    web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        command: npm run start
        container_name: frontend
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        ports:
            - "3000:3000"        
        volumes: 
            - ./:/app
            - /react-example/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
